chore!: bump msrv from 1.81 to 1.82 (#942)
## What changes are proposed in this pull request?
bump MSRV 1.81 to 1.82 (due to `Url` transitive deps bumping)
```
error: rustc 1.81.0 is not supported by the following packages:      
  │   icu_collections@2.0.0 requires rustc 1.82                            │
  │   icu_locale_core@2.0.0 requires rustc 1.82                            │
  │   icu_normalizer@2.0.0 requires rustc 1.82                             │
  │   icu_normalizer_data@2.0.0 requires rustc 1.82                        │
  │   icu_normalizer_data@2.0.0 requires rustc 1.82                        │
  │   icu_normalizer_data@2.0.0 requires rustc 1.82                        │
  │   icu_properties@2.0.0 requires rustc 1.82                             │
  │   icu_properties_data@2.0.0 requires rustc 1.82                        │
  │   icu_properties_data@2.0.0 requires rustc 1.82                        │
  │   icu_properties_data@2.0.0 requires rustc 1.82                        │
  │   icu_provider@2.0.0 requires rustc 1.82                               │
  │   idna_adapter@1.2.1 requires rustc 1.82                               │
  │   litemap@0.8.0 requires rustc 1.82                                    │
  │   zerotrie@0.2.2 requires rustc 1.82                                   │
  │   zerovec@0.11.2 requires rustc 1.82            
```

### This PR affects the following public APIs
MSRV increase to rustc 1.82


## How was this change tested?
MSRV tests

---------

Signed-off-by: R. Tyler Croy <rtyler@brokenco.de>
Co-authored-by: R. Tyler Croy <rtyler@brokenco.de>